### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by andreamari** [Scinawa/quantumalgorithms.org#60]
If you do a search for "??" at [this html page](https://quantumalgorithms.org/quantum-computing-and-quantum-algorithms.html) you'll find 4 references to theorems that are rendered as "??". 

Great project, congratulations!

**Comment by Scinawa** [comment]
🙏🙏🙏 thanks! Will fix soon :)

**Comment by Scinawa** [comment]
Fixed - b28d85cce4031ed84ac67f3a9edd0b02c8ad6bdd.
